on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@main
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55
          args: --timeout=30m
      - run:
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          verbose: true